### ISSUE TITLE
Finish the exercise

### ISSUE THREAD

**Issue by nasivuela** [Adalab/e-s1-evaluacion-intermedia-lauraferrandof#1]
Awesome job @lauraferrandof  !!
A well-organized exercise, clean and indented, with good HTML semantic, multiple CSS classes, CSS hierarchy, and good git commits!

Here you have some tips to improve the exercise.

- [x] Publish it on Github Pages and add the link next to repo description
- [x] Fix meta title
- [x] Avoid uppercase on HTML, we can transform the text with CSS
- [x] Avoid `br` tags, we can make the text jump with CSS ;) 
- [x] Reorder CSS links
- [x] Good job with CSS hierarchy! You can go further and add to `body` selector: font-size, font-weight, color, and background-color.
- [x] Finish the mobile version: the 75% height doesn't seem to work, and the title has to be bolder.
- [x] Go for tablet and desktop versions!

**Comment by lauraferrandof** [comment]
Hi @nasivuela , thank you for your feedback!!

I think I fixed everything you told me to. I also added a README file, a .gitignore and a license.

I still have to figure out a way to center the main title so that it doesn't look bad when you flip the viewport in the mobile version. And I'd like to find another way to stablish the header height so it adapts to its elements size, instead of setting a specific height for mobile or tablet version (I don't know if this is possible but I want to do some research about it).

Let me know if there's anything else that I can improve! :)

**Comment by lauraferrandof** [comment]
I think I fixed the main title centering! Although I don't understand why it works. I'll see if I can fix the header thing during the weekend!

**Comment by nasivuela** [comment]
Ole!

![](https://media.giphy.com/media/Hc8PMCBjo9BXa/giphy.gif)

About the main title, you are mixing two techniques to center it (flex and position), one should be enough, choose ;)

For the header height, you can do both, give it a fixed height, or let the content define it. It will depend on how accurate you want it to be ;)
